# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_39.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 633)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.simulate = QtWidgets.QWidget()
        self.simulate.setObjectName("simulate")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.simulate)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.modelProtocol = QtWidgets.QTableWidget(self.simulate)
        self.modelProtocol.setObjectName("modelProtocol")
        self.modelProtocol.setColumnCount(0)
        self.modelProtocol.setRowCount(0)
        self.gridLayout_3.addWidget(self.modelProtocol, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineN = QtWidgets.QLineEdit(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineN.sizePolicy().hasHeightForWidth())
        self.lineN.setSizePolicy(sizePolicy)
        self.lineN.setObjectName("lineN")
        self.verticalLayout.addWidget(self.lineN)
        self.checkBox_2 = QtWidgets.QCheckBox(self.simulate)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.simulate)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.label_3 = QtWidgets.QLabel(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.timeEdit = QtWidgets.QLineEdit(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_3.addWidget(self.timeEdit)
        self.checkBox_5 = QtWidgets.QCheckBox(self.simulate)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.startButton = QtWidgets.QPushButton(self.simulate)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_4.addWidget(self.startButton)
        self.progressBar = QtWidgets.QProgressBar(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(170, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(456, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.simulate, "")
        self.testing = QtWidgets.QWidget()
        self.testing.setObjectName("testing")
        self.gridLayout = QtWidgets.QGridLayout(self.testing)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.MplWidget = MplWidget(self.testing)
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout.addWidget(self.MplWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.testing, "")
        self.testingCorell = QtWidgets.QWidget()
        self.testingCorell.setObjectName("testingCorell")
        self.tabWidget.addTab(self.testingCorell, "")
        self.optimization = QtWidgets.QWidget()
        self.optimization.setObjectName("optimization")
        self.tabWidget.addTab(self.optimization, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 941, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Порог искажений"))
        self.lineN.setText(_translate("MainWindow", "6"))
        self.checkBox_2.setText(_translate("MainWindow", "Случайные процессы"))
        self.checkBox_3.setText(_translate("MainWindow", "Возмущающие процессы"))
        self.label_3.setText(_translate("MainWindow", "Время симуляции (сек)"))
        self.timeEdit.setText(_translate("MainWindow", "60.0"))
        self.checkBox_5.setText(_translate("MainWindow", "Сохранить в файл"))
        self.startButton.setText(_translate("MainWindow", "Моделирование"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simulate), _translate("MainWindow", "Симуляция модели"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testing), _translate("MainWindow", "Тестирование генераторов случайных велечин"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testingCorell), _translate("MainWindow", "Тестирование процедуры скользящего суммирования"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optimization), _translate("MainWindow", "Оптимизация"))

from graf import MplWidget
