# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_39.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 770)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.simulate = QtWidgets.QWidget()
        self.simulate.setObjectName("simulate")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.simulate)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.modelProtocol = QtWidgets.QTableWidget(self.simulate)
        self.modelProtocol.setObjectName("modelProtocol")
        self.modelProtocol.setColumnCount(0)
        self.modelProtocol.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.modelProtocol)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.isRandom = QtWidgets.QCheckBox(self.simulate)
        self.isRandom.setObjectName("isRandom")
        self.verticalLayout_3.addWidget(self.isRandom)
        self.isRandomCorel = QtWidgets.QCheckBox(self.simulate)
        self.isRandomCorel.setObjectName("isRandomCorel")
        self.verticalLayout_3.addWidget(self.isRandomCorel)
        self.label = QtWidgets.QLabel(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineN = QtWidgets.QLineEdit(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineN.sizePolicy().hasHeightForWidth())
        self.lineN.setSizePolicy(sizePolicy)
        self.lineN.setObjectName("lineN")
        self.verticalLayout_3.addWidget(self.lineN)
        self.label_3 = QtWidgets.QLabel(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.timeEdit = QtWidgets.QLineEdit(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEdit.sizePolicy().hasHeightForWidth())
        self.timeEdit.setSizePolicy(sizePolicy)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_3.addWidget(self.timeEdit)
        self.label_25 = QtWidgets.QLabel(self.simulate)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.label_25)
        self.qualityEdit = QtWidgets.QLineEdit(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qualityEdit.sizePolicy().hasHeightForWidth())
        self.qualityEdit.setSizePolicy(sizePolicy)
        self.qualityEdit.setObjectName("qualityEdit")
        self.verticalLayout_3.addWidget(self.qualityEdit)
        self.needFile = QtWidgets.QCheckBox(self.simulate)
        self.needFile.setObjectName("needFile")
        self.verticalLayout_3.addWidget(self.needFile)
        self.startButton = QtWidgets.QPushButton(self.simulate)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_3.addWidget(self.startButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self.simulate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(170, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(456, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.simulate, "")
        self.testing = QtWidgets.QWidget()
        self.testing.setObjectName("testing")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.testing)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.plot_fx = MplWidget(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_fx.sizePolicy().hasHeightForWidth())
        self.plot_fx.setSizePolicy(sizePolicy)
        self.plot_fx.setObjectName("plot_fx")
        self.verticalLayout_20.addWidget(self.plot_fx)
        self.plot_Fx = MplWidget(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_Fx.sizePolicy().hasHeightForWidth())
        self.plot_Fx.setSizePolicy(sizePolicy)
        self.plot_Fx.setObjectName("plot_Fx")
        self.verticalLayout_20.addWidget(self.plot_Fx)
        self.horizontalLayout_5.addLayout(self.verticalLayout_20)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.lineLamda_2 = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLamda_2.sizePolicy().hasHeightForWidth())
        self.lineLamda_2.setSizePolicy(sizePolicy)
        self.lineLamda_2.setObjectName("lineLamda_2")
        self.verticalLayout_12.addWidget(self.lineLamda_2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.lineM_2 = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineM_2.sizePolicy().hasHeightForWidth())
        self.lineM_2.setSizePolicy(sizePolicy)
        self.lineM_2.setObjectName("lineM_2")
        self.verticalLayout_11.addWidget(self.lineM_2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.lineSigma_2 = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSigma_2.sizePolicy().hasHeightForWidth())
        self.lineSigma_2.setSizePolicy(sizePolicy)
        self.lineSigma_2.setObjectName("lineSigma_2")
        self.verticalLayout_13.addWidget(self.lineSigma_2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.testing)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.m_edit = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_edit.sizePolicy().hasHeightForWidth())
        self.m_edit.setSizePolicy(sizePolicy)
        self.m_edit.setObjectName("m_edit")
        self.verticalLayout.addWidget(self.m_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.testing)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.N_edit = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N_edit.sizePolicy().hasHeightForWidth())
        self.N_edit.setSizePolicy(sizePolicy)
        self.N_edit.setObjectName("N_edit")
        self.verticalLayout_7.addWidget(self.N_edit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.label_24 = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_10.addWidget(self.label_24)
        self.tauEdit = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tauEdit.sizePolicy().hasHeightForWidth())
        self.tauEdit.setSizePolicy(sizePolicy)
        self.tauEdit.setObjectName("tauEdit")
        self.verticalLayout_10.addWidget(self.tauEdit)
        self.randMethod = QtWidgets.QComboBox(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randMethod.sizePolicy().hasHeightForWidth())
        self.randMethod.setSizePolicy(sizePolicy)
        self.randMethod.setObjectName("randMethod")
        self.randMethod.addItem("")
        self.randMethod.addItem("")
        self.randMethod.addItem("")
        self.verticalLayout_10.addWidget(self.randMethod)
        self.funcMethod = QtWidgets.QComboBox(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.funcMethod.sizePolicy().hasHeightForWidth())
        self.funcMethod.setSizePolicy(sizePolicy)
        self.funcMethod.setObjectName("funcMethod")
        self.funcMethod.addItem("")
        self.funcMethod.addItem("")
        self.verticalLayout_10.addWidget(self.funcMethod)
        self.CalcTestsButt = QtWidgets.QPushButton(self.testing)
        self.CalcTestsButt.setObjectName("CalcTestsButt")
        self.verticalLayout_10.addWidget(self.CalcTestsButt)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelSD = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSD.sizePolicy().hasHeightForWidth())
        self.labelSD.setSizePolicy(sizePolicy)
        self.labelSD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelSD.setObjectName("labelSD")
        self.horizontalLayout_6.addWidget(self.labelSD)
        self.editSD = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editSD.sizePolicy().hasHeightForWidth())
        self.editSD.setSizePolicy(sizePolicy)
        self.editSD.setObjectName("editSD")
        self.horizontalLayout_6.addWidget(self.editSD)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.editKolmag = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editKolmag.sizePolicy().hasHeightForWidth())
        self.editKolmag.setSizePolicy(sizePolicy)
        self.editKolmag.setObjectName("editKolmag")
        self.horizontalLayout_7.addWidget(self.editKolmag)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.verticalLayout_14.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.editPirs = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editPirs.sizePolicy().hasHeightForWidth())
        self.editPirs.setSizePolicy(sizePolicy)
        self.editPirs.setObjectName("editPirs")
        self.horizontalLayout_9.addWidget(self.editPirs)
        self.verticalLayout_17.addLayout(self.horizontalLayout_9)
        self.verticalLayout_14.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelCorel = QtWidgets.QLabel(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCorel.sizePolicy().hasHeightForWidth())
        self.labelCorel.setSizePolicy(sizePolicy)
        self.labelCorel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelCorel.setObjectName("labelCorel")
        self.horizontalLayout_10.addWidget(self.labelCorel)
        self.editCorel = QtWidgets.QLineEdit(self.testing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editCorel.sizePolicy().hasHeightForWidth())
        self.editCorel.setSizePolicy(sizePolicy)
        self.editCorel.setObjectName("editCorel")
        self.horizontalLayout_10.addWidget(self.editCorel)
        self.verticalLayout_18.addLayout(self.horizontalLayout_10)
        self.verticalLayout_14.addLayout(self.verticalLayout_18)
        self.verticalLayout_10.addLayout(self.verticalLayout_14)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.testing, "")
        self.testingCorell = QtWidgets.QWidget()
        self.testingCorell.setObjectName("testingCorell")
        self.gridLayout = QtWidgets.QGridLayout(self.testingCorell)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_corel = MplWidget(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_corel.sizePolicy().hasHeightForWidth())
        self.plot_corel.setSizePolicy(sizePolicy)
        self.plot_corel.setObjectName("plot_corel")
        self.gridLayout.addWidget(self.plot_corel, 0, 0, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_27.setSpacing(6)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_18 = QtWidgets.QLabel(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_27.addWidget(self.label_18)
        self.m_edit_2 = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_edit_2.sizePolicy().hasHeightForWidth())
        self.m_edit_2.setSizePolicy(sizePolicy)
        self.m_edit_2.setObjectName("m_edit_2")
        self.verticalLayout_27.addWidget(self.m_edit_2)
        self.horizontalLayout_16.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(6)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_22 = QtWidgets.QLabel(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_28.addWidget(self.label_22)
        self.N_edit_2 = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.N_edit_2.sizePolicy().hasHeightForWidth())
        self.N_edit_2.setSizePolicy(sizePolicy)
        self.N_edit_2.setObjectName("N_edit_2")
        self.verticalLayout_28.addWidget(self.N_edit_2)
        self.horizontalLayout_16.addLayout(self.verticalLayout_28)
        self.verticalLayout_23.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_19 = QtWidgets.QLabel(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_24.addWidget(self.label_19)
        self.yminEdit = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yminEdit.sizePolicy().hasHeightForWidth())
        self.yminEdit.setSizePolicy(sizePolicy)
        self.yminEdit.setObjectName("yminEdit")
        self.verticalLayout_24.addWidget(self.yminEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_20 = QtWidgets.QLabel(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_25.addWidget(self.label_20)
        self.ymaxEdit = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ymaxEdit.sizePolicy().hasHeightForWidth())
        self.ymaxEdit.setSizePolicy(sizePolicy)
        self.ymaxEdit.setObjectName("ymaxEdit")
        self.verticalLayout_25.addWidget(self.ymaxEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_25)
        self.verticalLayout_23.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_21 = QtWidgets.QLabel(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.dtEdit = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dtEdit.sizePolicy().hasHeightForWidth())
        self.dtEdit.setSizePolicy(sizePolicy)
        self.dtEdit.setObjectName("dtEdit")
        self.horizontalLayout_18.addWidget(self.dtEdit)
        self.verticalLayout_23.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.testingCorell)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.c0Edit = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c0Edit.sizePolicy().hasHeightForWidth())
        self.c0Edit.setSizePolicy(sizePolicy)
        self.c0Edit.setObjectName("c0Edit")
        self.verticalLayout_8.addWidget(self.c0Edit)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.testingCorell)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.c1Edit = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c1Edit.sizePolicy().hasHeightForWidth())
        self.c1Edit.setSizePolicy(sizePolicy)
        self.c1Edit.setObjectName("c1Edit")
        self.verticalLayout_9.addWidget(self.c1Edit)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_23.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.testingCorell)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_19.addWidget(self.label_15)
        self.c2Edit = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c2Edit.sizePolicy().hasHeightForWidth())
        self.c2Edit.setSizePolicy(sizePolicy)
        self.c2Edit.setObjectName("c2Edit")
        self.verticalLayout_19.addWidget(self.c2Edit)
        self.horizontalLayout_17.addLayout(self.verticalLayout_19)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_23 = QtWidgets.QLabel(self.testingCorell)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_22.addWidget(self.label_23)
        self.c3Edit = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c3Edit.sizePolicy().hasHeightForWidth())
        self.c3Edit.setSizePolicy(sizePolicy)
        self.c3Edit.setObjectName("c3Edit")
        self.verticalLayout_22.addWidget(self.c3Edit)
        self.horizontalLayout_17.addLayout(self.verticalLayout_22)
        self.verticalLayout_23.addLayout(self.horizontalLayout_17)
        self.CalcCorelTestButt = QtWidgets.QPushButton(self.testingCorell)
        self.CalcCorelTestButt.setObjectName("CalcCorelTestButt")
        self.verticalLayout_23.addWidget(self.CalcCorelTestButt)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.lineSmirnov = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSmirnov.sizePolicy().hasHeightForWidth())
        self.lineSmirnov.setSizePolicy(sizePolicy)
        self.lineSmirnov.setObjectName("lineSmirnov")
        self.horizontalLayout_8.addWidget(self.lineSmirnov)
        self.verticalLayout_23.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.lineStudent = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineStudent.sizePolicy().hasHeightForWidth())
        self.lineStudent.setSizePolicy(sizePolicy)
        self.lineStudent.setObjectName("lineStudent")
        self.horizontalLayout_14.addWidget(self.lineStudent)
        self.verticalLayout_23.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_15.addWidget(self.label_17)
        self.lineFisher = QtWidgets.QLineEdit(self.testingCorell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineFisher.sizePolicy().hasHeightForWidth())
        self.lineFisher.setSizePolicy(sizePolicy)
        self.lineFisher.setObjectName("lineFisher")
        self.horizontalLayout_15.addWidget(self.lineFisher)
        self.verticalLayout_23.addLayout(self.horizontalLayout_15)
        self.gridLayout.addLayout(self.verticalLayout_23, 0, 1, 1, 1)
        self.tabWidget.addTab(self.testingCorell, "")
        self.optimization = QtWidgets.QWidget()
        self.optimization.setObjectName("optimization")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.optimization)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_21.setSpacing(6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.optimumTable = QtWidgets.QTableWidget(self.optimization)
        self.optimumTable.setObjectName("optimumTable")
        self.optimumTable.setColumnCount(0)
        self.optimumTable.setRowCount(0)
        self.verticalLayout_21.addWidget(self.optimumTable)
        self.optimumOutTable = QtWidgets.QTableWidget(self.optimization)
        self.optimumOutTable.setObjectName("optimumOutTable")
        self.optimumOutTable.setColumnCount(0)
        self.optimumOutTable.setRowCount(0)
        self.verticalLayout_21.addWidget(self.optimumOutTable)
        self.horizontalLayout.addLayout(self.verticalLayout_21)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.isRandomOpt = QtWidgets.QCheckBox(self.optimization)
        self.isRandomOpt.setChecked(True)
        self.isRandomOpt.setTristate(False)
        self.isRandomOpt.setObjectName("isRandomOpt")
        self.verticalLayout_6.addWidget(self.isRandomOpt)
        self.isRandomCorelOpt = QtWidgets.QCheckBox(self.optimization)
        self.isRandomCorelOpt.setChecked(True)
        self.isRandomCorelOpt.setObjectName("isRandomCorelOpt")
        self.verticalLayout_6.addWidget(self.isRandomCorelOpt)
        self.label_26 = QtWidgets.QLabel(self.optimization)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_6.addWidget(self.label_26)
        self.qualityEdit_2 = QtWidgets.QLineEdit(self.optimization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qualityEdit_2.sizePolicy().hasHeightForWidth())
        self.qualityEdit_2.setSizePolicy(sizePolicy)
        self.qualityEdit_2.setObjectName("qualityEdit_2")
        self.verticalLayout_6.addWidget(self.qualityEdit_2)
        self.label_2 = QtWidgets.QLabel(self.optimization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineNmin = QtWidgets.QLineEdit(self.optimization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineNmin.sizePolicy().hasHeightForWidth())
        self.lineNmin.setSizePolicy(sizePolicy)
        self.lineNmin.setObjectName("lineNmin")
        self.horizontalLayout_13.addWidget(self.lineNmin)
        self.lineNmax = QtWidgets.QLineEdit(self.optimization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineNmax.sizePolicy().hasHeightForWidth())
        self.lineNmax.setSizePolicy(sizePolicy)
        self.lineNmax.setObjectName("lineNmax")
        self.horizontalLayout_13.addWidget(self.lineNmax)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.label_4 = QtWidgets.QLabel(self.optimization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.timeEditOpt = QtWidgets.QLineEdit(self.optimization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEditOpt.sizePolicy().hasHeightForWidth())
        self.timeEditOpt.setSizePolicy(sizePolicy)
        self.timeEditOpt.setObjectName("timeEditOpt")
        self.verticalLayout_6.addWidget(self.timeEditOpt)
        self.needFileOpt = QtWidgets.QCheckBox(self.optimization)
        self.needFileOpt.setObjectName("needFileOpt")
        self.verticalLayout_6.addWidget(self.needFileOpt)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.optButton = QtWidgets.QPushButton(self.optimization)
        self.optButton.setObjectName("optButton")
        self.verticalLayout_5.addWidget(self.optButton)
        self.calcOpt = QtWidgets.QPushButton(self.optimization)
        self.calcOpt.setObjectName("calcOpt")
        self.verticalLayout_5.addWidget(self.calcOpt)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.progressBar_2 = QtWidgets.QProgressBar(self.optimization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_2.sizePolicy().hasHeightForWidth())
        self.progressBar_2.setSizePolicy(sizePolicy)
        self.progressBar_2.setMinimumSize(QtCore.QSize(170, 0))
        self.progressBar_2.setMaximumSize(QtCore.QSize(456, 16777215))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_5.addWidget(self.progressBar_2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.optimization, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1096, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.isRandom.setText(_translate("MainWindow", "Случайные процессы"))
        self.isRandomCorel.setText(_translate("MainWindow", "Возмущающие процессы"))
        self.label.setText(_translate("MainWindow", "Порог искажений"))
        self.lineN.setText(_translate("MainWindow", "6"))
        self.label_3.setText(_translate("MainWindow", "Время симуляции (сек)"))
        self.timeEdit.setText(_translate("MainWindow", "60.0"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>Порог качества пакетов</p></body></html>"))
        self.qualityEdit.setText(_translate("MainWindow", "0.2"))
        self.needFile.setText(_translate("MainWindow", "Сохранить в файл"))
        self.startButton.setText(_translate("MainWindow", "Моделирование"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simulate), _translate("MainWindow", "Симуляция модели"))
        self.label_9.setText(_translate("MainWindow", "λ"))
        self.lineLamda_2.setText(_translate("MainWindow", "0.01"))
        self.label_8.setText(_translate("MainWindow", "m"))
        self.lineM_2.setText(_translate("MainWindow", "6"))
        self.label_10.setText(_translate("MainWindow", "σ"))
        self.lineSigma_2.setText(_translate("MainWindow", "3"))
        self.label_5.setText(_translate("MainWindow", "Кол-во интервалов"))
        self.m_edit.setText(_translate("MainWindow", "20"))
        self.label_6.setText(_translate("MainWindow", "Кол-во генерируемых чисел"))
        self.N_edit.setText(_translate("MainWindow", "2000"))
        self.label_24.setText(_translate("MainWindow", "Максимальное значение параметра τ для корреляционного момента"))
        self.tauEdit.setText(_translate("MainWindow", "1000"))
        self.randMethod.setItemText(0, _translate("MainWindow", "Метод серединных квадратов"))
        self.randMethod.setItemText(1, _translate("MainWindow", "Метод иррационального числа"))
        self.randMethod.setItemText(2, _translate("MainWindow", "Конгруэнтный метод"))
        self.funcMethod.setItemText(0, _translate("MainWindow", "Экспоненциальное распределение"))
        self.funcMethod.setItemText(1, _translate("MainWindow", "Нормальное распределение"))
        self.CalcTestsButt.setText(_translate("MainWindow", "Провести тест"))
        self.labelSD.setText(_translate("MainWindow", "Среднеквадратичное отклонение графиков:"))
        self.label_14.setText(_translate("MainWindow", "Критерий согласия Колмогорова:"))
        self.label_16.setText(_translate("MainWindow", "Критерий согласия Пирсона:"))
        self.labelCorel.setText(_translate("MainWindow", "Элементы последовательности независимы:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testing), _translate("MainWindow", "Тестирование генераторов случайных велечин"))
        self.label_18.setText(_translate("MainWindow", "Кол-во интервалов"))
        self.m_edit_2.setText(_translate("MainWindow", "20"))
        self.label_22.setText(_translate("MainWindow", "Кол-во генерируемых чисел"))
        self.N_edit_2.setText(_translate("MainWindow", "20000"))
        self.label_19.setText(_translate("MainWindow", "y min"))
        self.yminEdit.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "y max"))
        self.ymaxEdit.setText(_translate("MainWindow", "2"))
        self.label_21.setText(_translate("MainWindow", "dt"))
        self.dtEdit.setText(_translate("MainWindow", "0.1"))
        self.label_7.setText(_translate("MainWindow", "C0"))
        self.c0Edit.setText(_translate("MainWindow", "0.333333332979894"))
        self.label_12.setText(_translate("MainWindow", "C1"))
        self.c1Edit.setText(_translate("MainWindow", "0.000015350131228"))
        self.label_15.setText(_translate("MainWindow", "C2"))
        self.c2Edit.setText(_translate("MainWindow", "0.00000000070688"))
        self.label_23.setText(_translate("MainWindow", "C3"))
        self.c3Edit.setText(_translate("MainWindow", "0.000000000000033"))
        self.CalcCorelTestButt.setText(_translate("MainWindow", "Провести тест"))
        self.label_11.setText(_translate("MainWindow", "Критерий согласия Смирнова:"))
        self.label_13.setText(_translate("MainWindow", "Критерий согласия Стьюдента:"))
        self.label_17.setText(_translate("MainWindow", "Критерий согласия Фишера:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testingCorell), _translate("MainWindow", "Тестирование процедуры скользящего суммирования"))
        self.isRandomOpt.setText(_translate("MainWindow", "Случайные процессы"))
        self.isRandomCorelOpt.setText(_translate("MainWindow", "Возмущающие процессы"))
        self.label_26.setText(_translate("MainWindow", "Порог качества пакетов"))
        self.qualityEdit_2.setText(_translate("MainWindow", "0.2"))
        self.label_2.setText(_translate("MainWindow", "Диапазон порога искажений"))
        self.lineNmin.setText(_translate("MainWindow", "4"))
        self.lineNmax.setText(_translate("MainWindow", "10"))
        self.label_4.setText(_translate("MainWindow", "Время симуляции (сек)"))
        self.timeEditOpt.setText(_translate("MainWindow", "60.0"))
        self.needFileOpt.setText(_translate("MainWindow", "Сохранить в файл"))
        self.optButton.setText(_translate("MainWindow", "Моделирование диапазона"))
        self.calcOpt.setText(_translate("MainWindow", "Найти оптимальные решения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optimization), _translate("MainWindow", "Оптимизация"))

from graf import MplWidget
